-- MySQL Script generated by MySQL Workbench
-- Mon May 12 10:32:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forma_pagamento` (
  `id` INT NOT NULL,
  `preco_prato` DECIMAL(10,2) NOT NULL,
  `id_preco_prato` INT NOT NULL,
  `metodo_pagamento` INT NOT NULL,
  `id_metodo_pagamento` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `id_valor` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nome_prato_gastronomico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nome_prato_gastronomico` (
  `id` INT NOT NULL,
  `nome_prato_gastronomico` VARCHAR(60) NOT NULL,
  `feedback` VARCHAR(45) NOT NULL,
  `preco_prato` DECIMAL NOT NULL,
  `origem_prato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `preco_prato`
    FOREIGN KEY ()
    REFERENCES `mydb`.`forma_pagamento` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preco_prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preco_prato` (
  `id` INT NOT NULL,
  `forma_pagamento` INT NOT NULL,
  `tamanho_prato` INT NOT NULL,
  `id_forma_pagamento` INT NOT NULL,
  `ingredientes_prato` VARCHAR(45) NOT NULL,
  `id_ingredientes_prato` INT NOT NULL,
  `id_tamanho_prato` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback` (
  `id` INT NOT NULL,
  `qualidade_prato` INT NOT NULL,
  `id_qualidade_prato` INT NOT NULL,
  `nome_prato_gastronomico` VARCHAR(60) NOT NULL,
  `feedback` VARCHAR(45) NOT NULL,
  `id_feedback` INT NOT NULL,
  `id_nome_prato_gastronomico` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredientes_prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredientes_prato` (
  `id` INT NOT NULL,
  `preco_prato` DECIMAL(10,2) NOT NULL,
  `id_preco_prato` INT NOT NULL,
  `id_tamanho_prato` INT NOT NULL,
  `tamanho_prato` INT NOT NULL,
  `nome_prato` VARCHAR(60) NOT NULL,
  `id_nome_prato` INT NOT NULL,
  `origem_prato` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `mydb`.`opcoes_prato` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`opcoes_prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`opcoes_prato` (
  `id` INT NOT NULL,
  `feedback` VARCHAR(45) NOT NULL,
  `id_feedback` INT NOT NULL,
  `nome_prato` VARCHAR(60) NOT NULL,
  `id_nome_prato` INT NOT NULL,
  `preco_prato` DECIMAL(10,2) NOT NULL,
  `id_preco_prato` INT NOT NULL,
  `id_nome_prato` INT NOT NULL,
  `origem_prato` INT NOT NULL,
  `id_origem_prato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_preco_prato_idx` (`id_preco_prato` ASC) VISIBLE,
  INDEX `id_nome_prato_idx` (`id_nome_prato` ASC) VISIBLE,
  CONSTRAINT `id_preco_prato`
    FOREIGN KEY (`id_preco_prato`)
    REFERENCES `mydb`.`ingredientes_prato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_nome_prato`
    FOREIGN KEY (`id_nome_prato`)
    REFERENCES `mydb`.`ingredientes_prato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
